server:
  port : 8099

servlet:
  context-path: /

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB